tist:
  admin:
    system-name: Mgov框架訓練
    theme: training
    max-depart-level: 4
    filename-strategy: monthly
    system-id: CWIS
spring:
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: com.tist.jpa.dialect.Oracle11Dialect
    properties:
      javax:
        persistence:
          validation:
            mode: none
  freemarker:
    enabled: true
    cache: true
    prefix: ${tist.admin.theme}/
    suffix: .ftl
    settings:
      template_exception_handler: ignore
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  profiles:
    active: dev
  resources:
    cache:
      period: 86400s
  session:
    store-type: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jmx:
    enabled: false
server:
  servlet:
    session:
      cookie:
        name: PHPSESSIONID
      timeout: 1800s

